language: objective-c
before_script: 
  - export LANG=en_US.UTF-8
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script: "xcodebuild -workspace TravisTest.xcworkspace -scheme TravisTest -sdk iphonesimulator clean test | xcpretty -c && exit ${PIPESTATUS[0]}"
