language: objective-c
before_script: 
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod --version 0.32.1
  - pod install
script: "xcodebuild -workspace TravisTest.xcworkspace -scheme TravisTest -sdk iphonesimulator clean test | xcpretty -c && exit ${PIPESTATUS[0]}"
